import React from "react";
import { getPublicAudit } from "@/lib/publicAudit";
import Results from "@/components/Results";
import Link from "next/link";
import { notFound } from "next/navigation";
import { generateAISummary } from "@/lib/aiSummary";
import { AuditResult } from "@/lib/auditEngine";
import { Metadata } from "next";
import CopyLinkButton from "@/components/CopyLinkButton";

interface PageProps {
  params: { id: string };
}

/**
 * --- METADATA GENERATION ---
 * Dynamically constructs Open Graph and Twitter metadata to enable rich URL previews
 * when the audit is shared on social platforms.
 * 
 * Flow:
 * 1. Intercepts the request and fetches the audit data via Supabase.
 * 2. Injects the raw savings data into the dynamic strings.
 * 3. Uses a try/catch boundary so a database timeout doesn't crash the entire page route.
 */
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  try {
    const audit = await getPublicAudit(params.id);

    if (!audit) {
      return {
        title: "Audit Not Found - RateAI",
      };
    }

    const title = `Saved $${audit.total_monthly_savings.toLocaleString()}/month using RateAI`;
    const description = `AI stack optimization audit generated by RateAI.`;

    return {
      title,
      description,
      openGraph: {
        title,
        description,
        type: "website",
      },
      twitter: {
        card: "summary_large_image",
        title,
        description,
      },
    };
  } catch (error) {
    return {
      title: "Error Loading Audit - RateAI",
    };
  }
}

/**
 * --- PUBLIC AUDIT FLOW ---
 * This is the main entry point for the shared, read-only audit report page.
 * 
 * Execution Flow:
 * 1. Fetching: Retrieves the structured JSON report from Supabase server-side.
 * 2. Integrity Check: Validates the payload structure to prevent rendering crashes.
 * 3. Sanitization: Strips PII (email, company names, DB IDs) to protect user privacy.
 * 4. AI Generation: Dynamically generates a summary using the sanitized data.
 * 5. Rendering: Passes strictly clean data to the modular Results components and Share CTAs.
 */
export default async function PublicAuditPage({ params }: PageProps) {
  // Fetch the shared audit data from Supabase using the server-side function
  const audit = await getPublicAudit(params.id);

  if (!audit) {
    notFound();
  }

  // 3. Corrupted Audit Data Validation
  if (!audit.results || !Array.isArray(audit.results)) {
    console.error("[PUBLIC AUDIT] Data Corruption: results payload is missing or invalid array.");
    throw new Error("Audit data is corrupted and cannot be securely rendered.");
  }

  // --- PRIVACY SANITIZATION ---
  // The database payload may contain arbitrary or accidental PII (emails, raw user UUIDs, 
  // company tokens) introduced during the lead capture phase. 
  // 
  // We execute a strict "Allow-List" mapping over the array:
  // 1. Manually extract ONLY the necessary fields.
  // 2. Coerce types (String/Number) to guarantee no hidden object chains are leaked.
  // 3. This sanitized object is completely safe to pass to Third-Party AI APIs and public client browsers.
  const sanitizedResults: AuditResult[] = audit.results.map((r: any) => ({
    currentTool: String(r.currentTool || "Unknown Tool"),
    currentPlan: String(r.currentPlan || "Unknown Plan"),
    fitScore: Number(r.fitScore || 0),
    fitResult: {
      score: Number(r.fitResult?.score || 0),
      status: r.fitResult?.status || "appropriate",
      reasoning: Array.isArray(r.fitResult?.reasoning) ? r.fitResult.reasoning.map(String) : [],
    },
    cheaperSameVendor: r.cheaperSameVendor ? {
      recommendedPlan: String(r.cheaperSameVendor.recommendedPlan || ""),
      monthlySavings: Number(r.cheaperSameVendor.monthlySavings || 0),
      yearlySavings: Number(r.cheaperSameVendor.yearlySavings || 0),
      reason: String(r.cheaperSameVendor.reason || ""),
    } : undefined,
    alternatives: Array.isArray(r.alternatives) ? r.alternatives.map((alt: any) => ({
      tool: String(alt.tool || ""),
      plan: String(alt.plan || ""),
      estimatedSavings: Number(alt.estimatedSavings || 0),
      valueScore: Number(alt.valueScore || 0),
      reason: String(alt.reason || ""),
    })) : [],
    savings: {
      monthly: Number(r.savings?.monthly || 0),
      yearly: Number(r.savings?.yearly || 0),
      percentage: Number(r.savings?.percentage || 0),
    },
    finalRecommendation: String(r.finalRecommendation || ""),
    confidenceScore: Number(r.confidenceScore || 0),
    analysisDate: String(r.analysisDate || new Date().toISOString()),
  }));

  // Generate AI Summary Server-Side
  const aiSummaryData = await generateAISummary({
    totalMonthlySavings: audit.total_monthly_savings,
    totalAnnualSavings: audit.total_annual_savings,
    results: sanitizedResults,
  });

  const aiSummaryNode = (
    <section aria-labelledby="ai-summary-title" className="max-w-4xl mx-auto px-4 mb-12 animate-in fade-in slide-in-from-bottom-8 duration-700 delay-200">
      <div className="bg-white dark:bg-zinc-900 rounded-[2rem] p-8 md:p-10 border border-zinc-200 dark:border-zinc-800 shadow-sm relative overflow-hidden">
        <div className="absolute top-0 left-0 w-1.5 h-full bg-gradient-to-b from-blue-500 to-indigo-600" />
        <div className="flex items-center gap-3 mb-6">
          <div className="w-10 h-10 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 flex items-center justify-center rounded-xl shadow-inner" aria-hidden="true">
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M13 10V3L4 14h7v7l9-11h-7z" />
            </svg>
          </div>
          <h2 id="ai-summary-title" className="text-2xl font-black text-zinc-900 dark:text-white tracking-tight">AI Executive Summary</h2>
        </div>
        <p className="text-zinc-600 dark:text-zinc-300 text-lg leading-relaxed font-medium">
          {aiSummaryData.summary}
        </p>
        <div className="mt-6 flex items-center gap-2 text-[10px] uppercase font-black text-zinc-400 tracking-widest">
          <span className="flex w-2 h-2 rounded-full bg-green-500 animate-pulse" />
          Analyzed by {aiSummaryData.provider === 'anthropic' ? 'Claude 3.5 Sonnet' : aiSummaryData.provider === 'openai' ? 'GPT-4o' : 'RateAI Engine'}
        </div>
      </div>
    </section>
  );

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-black text-zinc-900 dark:text-zinc-100 font-sans selection:bg-blue-500/30 flex flex-col">
      {/* NAVIGATION - Minimalist & Fixed */}
      <nav aria-label="Main Navigation" className="fixed top-0 w-full z-50 bg-white/80 dark:bg-black/80 backdrop-blur-md border-b border-zinc-200 dark:border-zinc-800">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <Link href="/" aria-label="RateAI Home" className="flex items-center gap-2 group cursor-pointer transition-transform active:scale-95 focus:ring-4 focus:ring-blue-500/30 rounded-lg outline-none">
            <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center text-white font-black shadow-md group-hover:shadow-blue-500/50 transition-all">
              R
            </div>
            <span className="text-xl font-black tracking-tighter uppercase group-hover:text-blue-600 transition-colors">
              RateAI
            </span>
          </Link>
          <div className="flex items-center gap-4 text-xs font-black uppercase tracking-widest text-zinc-500">
            <span className="hidden sm:inline-block px-4 py-1.5 bg-blue-50 dark:bg-blue-900/20 text-blue-600 dark:text-blue-400 border border-blue-100 dark:border-blue-800/50 rounded-full shadow-inner">
              Shared Audit Report
            </span>
            <Link 
              href="/" 
              className="px-5 py-2 bg-zinc-900 dark:bg-white text-white dark:text-zinc-900 rounded-full hover:scale-105 transition-all active:scale-95 shadow-lg"
            >
              Run Audit
            </Link>
          </div>
        </div>
      </nav>

      {/* MAIN CONTENT */}
      <main className="flex-grow pt-32 pb-12">
        {/* CONTEXT HEADER */}
        <header className="max-w-6xl mx-auto px-4 mb-12 text-center animate-in fade-in slide-in-from-bottom-8 duration-700">
          <div className="inline-flex items-center gap-2 px-3 py-1 bg-green-50 dark:bg-green-900/20 border border-green-200 dark:border-green-800 rounded-full mb-6 text-green-600 dark:text-green-400" aria-hidden="true">
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span className="text-[10px] font-black uppercase tracking-[0.1em]">Verified Public Record</span>
          </div>
          
          <h1 className="text-4xl md:text-5xl font-black tracking-tight mb-4 text-zinc-900 dark:text-white">
            AI Infrastructure Audit
          </h1>
          
          <p className="text-zinc-400 text-xs mt-6 uppercase tracking-widest font-bold">
            Generated on <time dateTime={new Date(audit.created_at).toISOString()}>
              {new Date(audit.created_at).toLocaleDateString(undefined, {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
              })}
            </time>
          </p>
        </header>

        {/* REUSE HIGH-PERFORMANCE DASHBOARD COMPONENT */}
        <Results 
          results={sanitizedResults} 
          isLoading={false} 
          isPublicPage={true}
          aiSummaryNode={aiSummaryNode}
        />

        {/* SHARE CTA */}
        <section aria-labelledby="share-cta-title" className="max-w-4xl mx-auto px-4 mt-12 animate-in fade-in duration-700">
          <div className="p-8 bg-zinc-50 dark:bg-zinc-900/50 border border-zinc-200 dark:border-zinc-800 rounded-3xl flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="space-y-2 text-center md:text-left flex-1">
              <h3 id="share-cta-title" className="text-xl font-bold text-zinc-900 dark:text-white">Share this Audit</h3>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                Help others optimize their AI stack by sharing these insights.
              </p>
            </div>
            
            {/* SOCIAL ACTIONS (Responsive) */}
            <div className="flex flex-wrap items-center justify-center md:justify-end gap-3 w-full md:w-auto">
              <a 
                href={`https://twitter.com/intent/tweet?url=https://rateai.vercel.app/audit/${params.id}&text=Check%20out%20my%20custom%20AI%20Pricing%20Audit%21%20I%20could%20save%20%24${audit.total_monthly_savings}%2Fmonth.`} 
                target="_blank" 
                rel="noopener noreferrer"
                className="w-10 h-10 flex items-center justify-center rounded-full bg-black dark:bg-white text-white dark:text-black hover:scale-110 transition-transform shadow-md focus:ring-4 focus:ring-zinc-500/30 outline-none"
                aria-label="Share on X (Twitter)"
              >
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.008 5.92H5.078z"/></svg>
              </a>
              <a 
                href={`https://www.linkedin.com/sharing/share-offsite/?url=https://rateai.vercel.app/audit/${params.id}`} 
                target="_blank" 
                rel="noopener noreferrer"
                className="w-10 h-10 flex items-center justify-center rounded-full bg-[#0077b5] text-white hover:scale-110 transition-transform shadow-md focus:ring-4 focus:ring-blue-500/30 outline-none"
                aria-label="Share on LinkedIn"
              >
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24"><path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/></svg>
              </a>
              <div className="h-8 w-px bg-zinc-200 dark:bg-zinc-700 hidden md:block mx-2" />
              <CopyLinkButton id={params.id} />
            </div>
          </div>
        </section>

        {/* VIRAL ACQUISITION CTA */}
        <section aria-labelledby="viral-cta-title" className="max-w-4xl mx-auto px-4 mt-20 mb-8 animate-in fade-in duration-1000 delay-500">
          <div className="bg-gradient-to-r from-blue-600 to-indigo-700 rounded-[3rem] p-10 md:p-16 text-center shadow-2xl border border-blue-400/20 relative overflow-hidden group">
            <div className="absolute top-0 left-0 w-full h-full bg-[url('/noise.png')] opacity-10 mix-blend-overlay" aria-hidden="true" />
            <div className="absolute top-0 right-0 -mt-10 -mr-10 w-40 h-40 bg-white/10 rounded-full blur-3xl group-hover:bg-white/20 transition-all duration-700" aria-hidden="true" />
            
            <div className="relative z-10 space-y-6">
              <h2 id="viral-cta-title" className="text-3xl md:text-5xl font-black text-white tracking-tight">
                Are you overpaying for AI?
              </h2>
              <p className="text-blue-100 text-lg md:text-xl font-medium max-w-2xl mx-auto leading-relaxed">
                Run your own custom pricing audit in seconds. Discover hidden savings and optimize your tool stack for maximum ROI.
              </p>
              <div className="pt-4">
                <Link 
                  href="/"
                  className="inline-flex items-center justify-center px-10 py-5 bg-white text-blue-700 font-extrabold text-lg rounded-2xl hover:bg-blue-50 hover:scale-105 transition-all duration-300 active:scale-95 shadow-xl shadow-blue-900/20 focus:ring-4 focus:ring-white/50 outline-none"
                >
                  Start Free Audit
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      
      {/* GLOBAL FOOTER */}
      <footer role="contentinfo" className="border-t border-zinc-200 dark:border-zinc-800 py-12 bg-white dark:bg-black mt-auto">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center gap-8">
          <div className="flex items-center gap-3 opacity-50 hover:opacity-100 transition-opacity">
            <div className="w-8 h-8 bg-zinc-900 dark:bg-white rounded flex items-center justify-center text-white dark:text-zinc-900 font-black text-sm">R</div>
            <span className="text-base font-black tracking-tighter uppercase text-zinc-900 dark:text-white">RateAI</span>
          </div>
          <p className="text-zinc-500 text-[10px] font-black uppercase tracking-widest text-center">
            &copy; {new Date().getFullYear()} RateAI | A Credex Initiative
          </p>
          <div className="flex gap-8 text-[10px] font-black uppercase tracking-widest text-zinc-400">
            <a href="#" className="hover:text-blue-600 transition-colors">Privacy</a>
            <a href="#" className="hover:text-blue-600 transition-colors">Terms</a>
            <a href="#" className="hover:text-blue-600 transition-colors">Enterprise</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
